(function(){
'use strict';
const U=window.TravelUtils, Store=window.TravelStorage, Cloud=window.TravelCloudSync;
let state=Store.load(), view='dashboard', cloudLoading=true, autosaveTimer=null, community=[];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const titles={dashboard:'Tableau de bord',today:'Aujourd’hui',community:'Communauté',trip:'Voyage',map:'Carte du voyage',itinerary:'Planning',budget:'Budget',suggestions:'Suggestions',preparation:'Préparation',journal:'Carnet',settings:'Paramètres'};
const templates=[
 {name:'Roadtrip',style:'aventure',icon:'🚗',desc:'Étapes, trajets et pauses sur plusieurs jours.'},
 {name:'City break',style:'équilibré',icon:'🏙️',desc:'Week-end, activités, restaurants et hôtel.'},
 {name:'Voyage avion',style:'confort',icon:'✈️',desc:'Aéroports, transferts, hôtel et marge horaires.'},
 {name:'Petit budget',style:'économique',icon:'🎒',desc:'Budget serré, transports, repas et priorités.'}
];
function activeTrip(){return Store.getTrip(state)}
function saveLocal(){state=Store.save(state);}
function isSigned(){return !!Cloud.getUser()}
function show(msg,type='info'){const b=$('#statusBanner'); b.textContent=msg; b.className='status-banner '+type; b.hidden=false; clearTimeout(show.t); show.t=setTimeout(()=>b.hidden=true,3200)}
function scheduleSave(){saveLocal(); clearTimeout(autosaveTimer); autosaveTimer=setTimeout(async()=>{ if(isSigned()){try{await Cloud.saveState(state); renderAccount();}catch(e){show('Sauvegarde impossible : '+(e.message||e),'error')}}},500)}
function persist(msg){saveLocal(); renderAll(); scheduleSave(); if(msg)show(msg)}
function esc(s){return U.esc(s)}
function budget(trip){const expenses=trip?.expenses||[]; const planned=expenses.reduce((a,e)=>a+U.num(e.planned),0)+(trip?.steps||[]).reduce((a,s)=>a+U.num(s.cost),0); const actual=expenses.reduce((a,e)=>a+U.num(e.actual),0); const max=U.num(trip?.maxBudget); return {planned,actual,total:actual||planned,max,remaining:max-(actual||planned)};}
function score(trip){if(!trip)return 0; let pts=0,max=8; if(trip.name)pts++; if(trip.area)pts++; if(trip.startDate&&trip.endDate)pts++; if((trip.steps||[]).length>=2)pts++; if((trip.expenses||[]).length)pts++; if((trip.checklists||[]).some(b=>(b.items||[]).some(i=>i.done)))pts++; if((trip.steps||[]).every(s=>s.arrivalDate&&s.departureDate))pts++; if(U.num(trip.maxBudget)>0)pts++; return Math.round(pts/max*100)}
function init(){bind(); applyTheme(state.settings.theme); renderAll(); switchView(location.hash.replace('#','')||'dashboard'); initCloud();}
function bind(){
 $$('[data-view-link]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.viewLink)));
 window.addEventListener('hashchange',()=>switchView(location.hash.replace('#','')||'dashboard'));
 $('#newTripBtn').addEventListener('click',newTrip); $('#createFirstTripBtn').addEventListener('click',newTrip);
 $('#themeToggle').addEventListener('click',()=>{state.settings.theme=document.body.classList.contains('dark')?'light':'dark'; applyTheme(state.settings.theme); persist('Thème modifié.')});
 $('#cloudAuthBtn').addEventListener('click',async()=>{try{isSigned()?await Cloud.signOut():await Cloud.signIn()}catch(e){show('Connexion impossible : '+(e.message||e),'error')}});
 $('#tripSelector').addEventListener('change',e=>{state.activeTripId=e.target.value||null; persist('Voyage sélectionné.')});
 $('#tripForm').addEventListener('submit',saveTripForm); $('#addStepBtn').addEventListener('click',()=>openStep()); $('#stepForm').addEventListener('submit',saveStep);
 $('#addExpenseBtn').addEventListener('click',()=>openExpense()); $('#expenseForm').addEventListener('submit',saveExpense);
 $('#fitMapBtn').addEventListener('click',renderMap); $('#refreshItineraryBtn').addEventListener('click',renderItinerary);
 $('#settingsForm').addEventListener('submit',saveSettings); $('#addChecklistBlockBtn').addEventListener('click',addChecklistBlock); $('#autoFixBtn').addEventListener('click',autoFix);
 $('#communityPublishBtn').addEventListener('click',openPublish); $('#communityRefreshBtn').addEventListener('click',loadCommunity); $('#publishForm').addEventListener('submit',publishCommunity);
 ['communitySearchInput','communityCountryFilter','communityCategoryFilter','communitySortFilter'].forEach(id=>$('#'+id)?.addEventListener('input',renderCommunity));
 $('#globalSearchInput').addEventListener('input',renderSearch);
 $('#fabBtn').addEventListener('click',()=>$('#fabMenu').hidden=!$('#fabMenu').hidden); $('#fabMenu').addEventListener('click',e=>{const a=e.target.dataset.fab;if(!a)return; $('#fabMenu').hidden=true; if(a==='trip')newTrip(); if(a==='step')openStep(); if(a==='expense')openExpense(); if(a==='today')switchView('today')});
 $$('[data-close-dialog]').forEach(b=>b.addEventListener('click',()=>$('#'+b.dataset.closeDialog)?.close()));
 $('#geocodeBtn').addEventListener('click',geocode);
 document.addEventListener('click',delegated);
}
async function initCloud(){
 Cloud.onAuthChange(({user})=>{renderAuth(user); renderAccount();});
 try{await Cloud.init(); await Cloud.waitForAuthState(); if(Cloud.getUser()){const remote=await Cloud.loadState(); if(remote?.state)state=Store.normalize(remote.state); saveLocal();} cloudLoading=false; renderAll(); if(Cloud.getUser())loadCommunity();}
 catch(e){cloudLoading=false; show('Firebase : '+(e.message||e),'error'); renderAll();}
}
function renderAuth(user=Cloud.getUser()){
 const btn=$('#cloudAuthBtn'); const av=btn.querySelector('.auth-avatar'); const copy=btn.querySelector('.auth-copy'); btn.classList.toggle('is-connected',!!user);
 if(user){av.innerHTML=user.photoURL?`<img src="${esc(user.photoURL)}" alt="">`:'✓'; copy.innerHTML=`<strong>Connecté</strong><small>${esc((user.displayName||user.email||'Google').split(' ')[0])}</small>`;}
 else{av.textContent='G'; copy.innerHTML='<strong>Connexion</strong><small>Google</small>';}
}
function applyTheme(t){document.body.classList.toggle('dark',t==='dark'); $('#themeToggle').textContent=t==='dark'?'☀️':'🌙'}
function switchView(v){if(!titles[v])v='dashboard'; view=v; if(location.hash.replace('#','')!==v)location.hash=v; $$('.view').forEach(s=>s.classList.toggle('is-visible',s.id===`view-${v}`)); $$('.nav-item').forEach(n=>n.classList.toggle('is-active',n.dataset.viewLink===v)); $('#pageTitle').textContent=titles[v]; renderAll();}
function renderAll(){renderSelector();renderDashboard();renderToday();renderTripForm();renderSteps();renderMap();renderItinerary();renderBudget();renderSuggestions();renderPreparation();renderJournal();renderAccount();renderSettings();renderCommunity();}
function renderSelector(){const sel=$('#tripSelector'); sel.innerHTML=state.trips.length?state.trips.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join(''):'<option value="">Aucun voyage</option>'; sel.value=state.activeTripId||'';}
function loginGate(){return `<div class="login-gate"><h2>Connexion Google</h2><p>Connecte-toi pour charger tes voyages Firebase et synchroniser chaque modification.</p><button class="button button--primary" data-action="signin">Se connecter avec Google</button></div>`}
function renderDashboard(){
 const t=activeTrip(), user=Cloud.getUser(), b=t?budget(t):null, s=t?score(t):0;
 $('#dashboardHero').style.setProperty('--hero-img',t?.coverImage?`url('${t.coverImage.replace(/'/g,'%27')}')`: 'linear-gradient(135deg,#0b3b66,#0ea5a7)');
 $('#dashboardHero').innerHTML=user&&t?`<div><p class="eyebrow">Voyage actif</p><h2>${esc(t.name)}</h2><p>${esc(t.description||'Ton centre de contrôle pour préparer et suivre le voyage.')}</p><div class="button-row"><button class="button button--primary" data-go="today">Mode voyage</button><button class="button" data-go="itinerary">Planning</button><button class="button" data-go="budget">Budget</button></div></div><div class="hero-metrics"><div class="hero-metric"><small>Préparation</small><strong>${s}%</strong></div><div class="hero-metric"><small>Budget</small><strong>${U.money(b.total,t.currency)}</strong></div><div class="hero-metric"><small>Étapes</small><strong>${(t.steps||[]).length}</strong></div><div class="hero-metric"><small>Durée</small><strong>${U.daysBetween(t.startDate,t.endDate)||'—'} j</strong></div></div>`:`<div><p class="eyebrow">Travel Planner</p><h2>Planifie tes voyages avec Google</h2><p>Planning, budget, carte, préparation, communauté et carnet dans une interface propre.</p><div class="button-row"><button class="button button--primary" data-action="signin">Se connecter</button><button class="button" data-action="newTrip">Créer un voyage</button></div></div><div class="hero-metrics"><div class="hero-metric"><small>Cloud</small><strong>Firebase</strong></div><div class="hero-metric"><small>Créé par</small><strong>Lucas S.</strong></div></div>`;
 $('#tripTemplates').innerHTML=templates.map(x=>`<button class="template-card" data-template="${esc(x.name)}"><strong>${x.icon} ${esc(x.name)}</strong><span class="muted">${esc(x.desc)}</span></button>`).join('');
 const grid=$('#tripsGrid'); if(cloudLoading){grid.innerHTML='<div class="empty-state">Chargement de Firebase…</div>';return;} if(!user){grid.innerHTML=loginGate();return;} if(!state.trips.length){grid.innerHTML='<div class="empty-state">Aucun voyage. Crée ton premier itinéraire.</div>';return;}
 grid.innerHTML=state.trips.map(trip=>{const bu=budget(trip), sc=score(trip); const cover=trip.coverImage?`style="background-image:url('${esc(trip.coverImage)}')"`:''; return `<article class="trip-card"><div class="trip-card__cover" ${cover}></div><div class="trip-card__body"><div class="row-head"><div><span class="badge">${esc(trip.status)}</span><h3>${esc(trip.name)}</h3></div><strong>${sc}%</strong></div><p class="muted">${esc(trip.area||'Zone non renseignée')} · ${U.dateLabel(trip.startDate)} → ${U.dateLabel(trip.endDate)}</p><div class="meta-grid"><span class="meta-pill">🧭 ${(trip.steps||[]).length} étapes</span><span class="meta-pill">💶 ${U.money(bu.total,trip.currency)}</span><span class="meta-pill">👥 ${trip.travellers||1}</span><span class="meta-pill">🎯 ${esc(trip.style)}</span></div><div class="button-row"><button class="button button--primary" data-open-trip="${trip.id}">Continuer</button><button class="button" data-dup-trip="${trip.id}">Dupliquer</button><button class="button button--danger" data-del-trip="${trip.id}">Supprimer</button></div></div></article>`}).join('');
}
function newTrip(){if(!isSigned()){Cloud.signIn().catch(e=>show(e.message,'error'));return;} const trip=Store.createTrip(); state.trips.push(trip); state.activeTripId=trip.id; persist('Voyage créé.'); switchView('trip');}
function renderTripForm(){const f=$('#tripForm'), t=activeTrip(); f.querySelectorAll('input,select,textarea,button').forEach(el=>el.disabled=!t); if(!t){f.reset();return;} ['name','area','coverImage','startDate','endDate','travellers','maxBudget','currency','status','style','pace','interests','description'].forEach(k=>{if(f.elements[k])f.elements[k].value=t[k]??''}); f.elements.travellersNames.value=(t.travellersNames||[]).join(', ');}
function saveTripForm(e){e.preventDefault();const t=activeTrip();if(!t)return; const f=e.target; ['name','area','coverImage','startDate','endDate','currency','status','style','pace','interests','description'].forEach(k=>t[k]=f.elements[k]?.value||''); t.travellers=U.num(f.elements.travellers.value)||1; t.travellersNames=U.parsePeople(f.elements.travellersNames.value); t.maxBudget=U.num(f.elements.maxBudget.value); persist('Voyage enregistré.');}
function renderSteps(){const box=$('#stepsList'),t=activeTrip(); if(!t){box.innerHTML='<div class="empty-state">Sélectionne un voyage.</div>';return;} if(!t.steps.length){box.innerHTML='<div class="empty-state">Ajoute le départ, les étapes et la destination.</div>';return;} box.innerHTML=t.steps.map((s,i)=>`<article class="step-row"><div class="row-head"><div><span class="badge">${i+1}. ${esc(s.type)}</span><h3>${esc(s.name)}</h3><p class="muted">${esc(s.address||'Adresse à préciser')}</p></div><div class="button-row"><button class="button" data-edit-step="${s.id}">Modifier</button><button class="button" data-up-step="${s.id}">↑</button><button class="button" data-down-step="${s.id}">↓</button><button class="button button--danger" data-del-step="${s.id}">Supprimer</button></div></div><div class="meta-grid"><span class="meta-pill">Arrivée ${U.shortDate(s.arrivalDate)} ${s.arrivalTime||''}</span><span class="meta-pill">Départ ${U.shortDate(s.departureDate)} ${s.departureTime||''}</span><span class="meta-pill">💶 ${U.money(s.cost,t.currency)}</span><span class="meta-pill">${esc(s.priority)}</span></div></article>`).join('')}
function openStep(id){const t=activeTrip(); if(!t)return show('Crée un voyage avant d’ajouter une étape.','error'); const s=id?t.steps.find(x=>x.id===id):Store.normalizeStep({}); const f=$('#stepForm'); f.reset(); Object.keys(s).forEach(k=>{if(f.elements[k])f.elements[k].value=s[k]??''}); $('#stepDialogTitle').textContent=id?'Modifier une étape':'Ajouter une étape'; $('#stepDialog').showModal();}
function saveStep(e){e.preventDefault();const t=activeTrip(),f=e.target;if(!t)return; const s=Store.normalizeStep(Object.fromEntries(new FormData(f).entries())); if(s.departureDate&&s.arrivalDate&&s.departureDate<s.arrivalDate){show('Le départ ne peut pas être avant l’arrivée.','error');return;} if(s.departureDate===s.arrivalDate&&s.departureTime&&s.arrivalTime&&s.departureTime<s.arrivalTime){show('L’heure de départ ne peut pas être avant l’arrivée.','error');return;} const i=t.steps.findIndex(x=>x.id===s.id); i>=0?t.steps[i]=s:t.steps.push(s); $('#stepDialog').close(); persist('Étape enregistrée.');}
async function geocode(){const q=$('#stepForm').elements.search.value.trim(), out=$('#geocodeResults'); if(!q)return; out.innerHTML='<span class="muted">Recherche…</span>'; try{const url=`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=5&addressdetails=1&q=${encodeURIComponent(q)}`; const res=await fetch(url,{headers:{'Accept':'application/json'}}); const data=await res.json(); out.innerHTML=data.length?data.map(r=>`<button type="button" data-geo='${esc(JSON.stringify({name:r.name||r.display_name.split(',')[0],address:r.display_name,lat:r.lat,lng:r.lon}))}'>${esc(r.display_name)}</button>`).join(''):'<span class="muted">Aucun résultat.</span>'; }catch(e){out.innerHTML='<span class="danger">Recherche impossible.</span>'}}
function renderMap(){const t=activeTrip(), canvas=$('#mapCanvas'), seg=$('#mapSegments'); if(!t||!t.steps.length){canvas.innerHTML='<div class="empty-state">Ajoute des étapes avec coordonnées pour voir la carte.</div>'; seg.innerHTML=''; return;} const pts=t.steps.map((s,i)=>({...s,i,lat:U.num(s.lat),lng:U.num(s.lng)})).filter(p=>p.lat&&p.lng); if(!pts.length){canvas.innerHTML='<div class="empty-state">Aucune coordonnée GPS disponible.</div>'; seg.innerHTML='';return;} const minLat=Math.min(...pts.map(p=>p.lat)), maxLat=Math.max(...pts.map(p=>p.lat)), minLng=Math.min(...pts.map(p=>p.lng)), maxLng=Math.max(...pts.map(p=>p.lng)); const pad=40,w=900,h=560; const x=p=>pad+(p.lng-minLng)/(maxLng-minLng||1)*(w-pad*2); const y=p=>h-pad-(p.lat-minLat)/(maxLat-minLat||1)*(h-pad*2); const path=pts.map((p,i)=>`${i?'L':'M'} ${x(p)} ${y(p)}`).join(' '); canvas.innerHTML=`<svg class="map-svg" viewBox="0 0 ${w} ${h}" role="img" aria-label="Carte du voyage"><defs><linearGradient id="sea" x1="0" x2="1"><stop stop-color="#dff6f2"/><stop offset="1" stop-color="#e9f0ff"/></linearGradient></defs><rect width="${w}" height="${h}" fill="url(#sea)"/><g opacity=".28" stroke="#0b3b66" stroke-width="1">${Array.from({length:14},(_,i)=>`<path d="M0 ${i*45} C180 ${i*45+40}, 360 ${i*45-35}, 900 ${i*45+10}" fill="none"/>`).join('')}</g><path d="${path}" fill="none" stroke="#0b3b66" stroke-width="4" stroke-linecap="round" stroke-dasharray="${pts.length>1?'0':'8'}"/>${pts.map(p=>`<g class="map-marker" transform="translate(${x(p)},${y(p)})"><circle r="18" fill="#0ea5a7"/><circle r="12" fill="#fff"/><text text-anchor="middle" dominant-baseline="middle" font-size="12" font-weight="900" fill="#0b3b66">${p.i+1}</text></g>`).join('')}</svg>`; $('#openOsmBtn').href=`https://www.openstreetmap.org/?mlat=${pts[0].lat}&mlon=${pts[0].lng}#map=6/${pts[0].lat}/${pts[0].lng}`; seg.innerHTML=t.steps.slice(1).map((s,i)=>{const a=t.steps[i]; const dist=(a.lat&&s.lat)?U.haversine(a,s):0; return `<article class="segment-card"><strong>${esc(a.name)} → ${esc(s.name)}</strong><span class="muted">${dist?dist.toFixed(0)+' km':'Distance à préciser'} · ${U.shortDate(s.arrivalDate)} ${s.arrivalTime||''}</span></article>`}).join('')||'<div class="empty-state">Ajoute au moins deux étapes.</div>';}
function renderItinerary(){const t=activeTrip(), box=$('#itineraryTimeline'); if(!t){box.innerHTML='<div class="empty-state">Aucun voyage.</div>';return;} const days={}; t.steps.forEach(s=>{const d=s.arrivalDate||'non daté'; (days[d] ||= []).push(s)}); box.innerHTML=Object.entries(days).map(([d,steps])=>`<div class="day-card"><h3>${d==='non daté'?'Étapes non datées':U.dateLabel(d)}</h3>${steps.sort((a,b)=>(a.arrivalTime||'99:99').localeCompare(b.arrivalTime||'99:99')).map(s=>`<div class="timeline-item"><strong>${s.arrivalTime||'--:--'} · ${esc(s.name)}</strong><p class="muted">${esc(s.type)} · départ ${s.departureTime||'--:--'} · ${esc(s.address||'')}</p></div>`).join('')}<button class="button" data-add-step-date="${d==='non daté'?'':d}">+ Ajouter dans cette journée</button></div>`).join('')||'<div class="empty-state">Aucune étape.</div>';}
function renderToday(){const t=activeTrip(), hero=$('#todayHero'), actions=$('#todayActions'), line=$('#todayTimeline'); if(!t){hero.innerHTML='<h2>Aucun voyage actif</h2>';actions.innerHTML='';line.innerHTML='';return;} const today=new Date().toISOString().slice(0,10); const upcoming=[...t.steps].filter(s=>!s.arrivalDate||s.arrivalDate>=today).sort((a,b)=>(a.arrivalDate+a.arrivalTime).localeCompare(b.arrivalDate+b.arrivalTime)); const next=upcoming[0]||t.steps[0]; hero.innerHTML=`<p class="eyebrow">Mode voyage</p><h2>${next?esc(next.name):'Aucune prochaine étape'}</h2><p>${next?`${U.dateLabel(next.arrivalDate)} ${next.arrivalTime||''} · ${esc(next.address||'Adresse à préciser')}`:'Ajoute une étape pour préparer la journée.'}</p>`; actions.innerHTML=`<h3>Actions rapides</h3><div class="button-row"><button class="button button--primary" data-action="step">+ Étape</button><button class="button" data-action="expense">+ Dépense</button><button class="button" data-go="map">Carte</button></div>`; line.innerHTML=`<h3>Prochaines étapes</h3>${upcoming.slice(0,6).map(s=>`<div class="timeline-item"><strong>${U.shortDate(s.arrivalDate)} ${s.arrivalTime||''} · ${esc(s.name)}</strong><p class="muted">${esc(s.address||'')}</p></div>`).join('')||'<div class="empty-state">Aucune étape à venir.</div>'}`;}
function openExpense(id){const f=$('#expenseForm'); f.reset(); const t=activeTrip(); const e=id?t.expenses.find(x=>x.id===id):{}; if(e)Object.keys(e).forEach(k=>{if(f.elements[k])f.elements[k].value=Array.isArray(e[k])?e[k].join(', '):e[k]}); $('#expenseDialog').showModal();}
function saveExpense(e){e.preventDefault(); const t=activeTrip(), f=e.target; if(!t)return; const exp=Store.normalizeExpense(Object.fromEntries(new FormData(f).entries())); const i=t.expenses.findIndex(x=>x.id===exp.id); i>=0?t.expenses[i]=exp:t.expenses.push(exp); $('#expenseDialog').close(); persist('Dépense enregistrée.');}
function renderBudget(){const t=activeTrip(); const sum=$('#budgetSummary'), list=$('#expensesList'), set=$('#settlementsBox'); if(!t){sum.innerHTML='';list.innerHTML='<div class="empty-state">Aucun voyage.</div>';set.innerHTML='';return;} const b=budget(t); sum.innerHTML=`<div class="stat"><small>Prévu</small><strong>${U.money(b.planned,t.currency)}</strong></div><div class="stat"><small>Réel</small><strong>${U.money(b.actual,t.currency)}</strong></div><div class="stat"><small>Budget max</small><strong>${U.money(b.max,t.currency)}</strong></div><div class="stat"><small>Reste</small><strong class="${b.remaining<0?'danger':'good'}">${U.money(b.remaining,t.currency)}</strong></div>`; list.innerHTML=t.expenses.map(e=>`<div class="expense-row"><div class="row-head"><strong>${esc(e.label)}</strong><div><button class="button" data-edit-expense="${e.id}">Modifier</button><button class="button button--danger" data-del-expense="${e.id}">Supprimer</button></div></div><span class="muted">${esc(e.category)} · prévu ${U.money(e.planned,t.currency)} · réel ${U.money(e.actual,t.currency)} · payé par ${esc(e.paidBy||'—')}</span></div>`).join('')||'<div class="empty-state">Aucune dépense.</div>'; renderSettlements(t,set);}
function renderSettlements(t,box){const people=t.travellersNames?.length?t.travellersNames:[...new Set(t.expenses.flatMap(e=>[e.paidBy,...(e.sharedWith||[])].filter(Boolean)))]; if(!people.length){box.innerHTML='<p class="muted">Ajoute les prénoms voyageurs et les dépenses payées.</p>';return;} const balance=Object.fromEntries(people.map(p=>[p,0])); t.expenses.forEach(e=>{const amount=U.num(e.actual)||U.num(e.planned); const shared=(e.sharedWith||[]).length?e.sharedWith:people; if(!amount||!e.paidBy)return; balance[e.paidBy]=(balance[e.paidBy]||0)+amount; const part=amount/shared.length; shared.forEach(p=>balance[p]=(balance[p]||0)-part);}); const creditors=Object.entries(balance).filter(([,v])=>v>0.01).sort((a,b)=>b[1]-a[1]); const debtors=Object.entries(balance).filter(([,v])=>v<-0.01).sort((a,b)=>a[1]-b[1]); const moves=[]; debtors.forEach(([d,v])=>{let owe=-v; creditors.forEach(c=>{if(owe<=.01||c[1]<=.01)return; const m=Math.min(owe,c[1]); moves.push(`${esc(d)} doit ${U.money(m,t.currency)} à ${esc(c[0])}`); owe-=m; c[1]-=m;});}); box.innerHTML=`<div class="table-list">${Object.entries(balance).map(([p,v])=>`<div class="meta-pill">${esc(p)} : ${U.money(v,t.currency)}</div>`).join('')}</div><hr>${moves.map(m=>`<div class="step-row">${m}</div>`).join('')||'<p class="good">Comptes équilibrés.</p>'}`;}
function suggestions(t=activeTrip()){if(!t)return[]; const out=[]; const b=budget(t); if(b.max&&b.total>b.max)out.push({type:'critical',title:'Budget dépassé',text:`Le budget dépasse de ${U.money(b.total-b.max,t.currency)}.`}); if(t.steps.length<2)out.push({type:'warn',title:'Itinéraire incomplet',text:'Ajoute au moins un départ et une destination.'}); t.steps.forEach(s=>{if(!s.address&&!s.lat)out.push({type:'warn',title:'Adresse manquante',text:`${s.name} n’a pas d’adresse ou coordonnées.`}); if(s.departureDate&&s.arrivalDate&&s.departureDate<s.arrivalDate)out.push({type:'critical',title:'Dates incohérentes',text:`${s.name} : départ avant arrivée.`}); if(s.departureDate===s.arrivalDate&&s.departureTime&&s.arrivalTime&&s.departureTime<s.arrivalTime)out.push({type:'critical',title:'Horaires incohérents',text:`${s.name} : heure de départ avant arrivée.`});}); if(t.style==='économique'&&b.max&&b.total>b.max*.75)out.push({type:'warn',title:'Style économique',text:'Tu approches fortement de ton budget maximum.'}); if(t.style==='confort')out.push({type:'good',title:'Style confort',text:'Vérifie les transferts aéroport/hôtel et les marges horaires.'}); if(!out.length)out.push({type:'good',title:'Voyage cohérent',text:'Aucune alerte majeure détectée.'}); return out;}
function renderSuggestions(){const t=activeTrip(); const sc=$('#suggestionsScore'), list=$('#suggestionsList'); if(!t){sc.innerHTML='';list.innerHTML='<div class="empty-state">Aucun voyage.</div>';return;} const items=suggestions(t), s=score(t); sc.innerHTML=`<div class="stat"><small>Score global</small><strong>${s}%</strong></div><div class="stat"><small>Alertes critiques</small><strong>${items.filter(i=>i.type==='critical').length}</strong></div><div class="stat"><small>À vérifier</small><strong>${items.filter(i=>i.type==='warn').length}</strong></div><div class="stat"><small>Bons points</small><strong>${items.filter(i=>i.type==='good').length}</strong></div>`; list.innerHTML=items.map(i=>`<article class="suggestion-card ${i.type}"><strong>${esc(i.title)}</strong><p>${esc(i.text)}</p><button class="button" data-action="taskFromSuggestion">Ajouter tâche</button></article>`).join('')}
function autoFix(){const t=activeTrip(); if(!t)return; let changed=false; t.steps.forEach(s=>{if(s.arrivalDate&&!s.departureDate){s.departureDate=s.arrivalDate;changed=true} if(s.departureDate&&s.arrivalDate&&s.departureDate<s.arrivalDate){s.departureDate=s.arrivalDate;changed=true}}); if(changed)persist('Corrections automatiques appliquées.'); else show('Aucune correction sûre à appliquer.');}
function renderPreparation(){const t=activeTrip(), box=$('#checklists'); if(!t){box.innerHTML='';return;} box.innerHTML=t.checklists.map(b=>`<div class="panel"><div class="row-head"><input class="input" value="${esc(b.title)}" data-check-title="${b.id}"><button class="button button--danger" data-del-check-block="${b.id}">Supprimer</button></div>${(b.items||[]).map(i=>`<label class="check"><input type="checkbox" ${i.done?'checked':''} data-check-item="${b.id}:${i.id}"><input class="input" value="${esc(i.text)}" data-check-text="${b.id}:${i.id}"><button class="button button--danger" data-del-check-item="${b.id}:${i.id}" type="button">×</button></label>`).join('')}<button class="button" data-add-check-item="${b.id}">+ Tâche</button></div>`).join('')}
function addChecklistBlock(){const t=activeTrip(); if(!t)return; t.checklists.push({id:U.uid(),title:'Nouveau bloc',items:[]}); persist('Bloc ajouté.');}
function renderJournal(){const t=activeTrip(), box=$('#journalList'); if(!t){box.innerHTML='';return;} box.innerHTML=t.steps.map(s=>`<div class="panel"><h3>${esc(s.name)}</h3><textarea class="input" rows="5" data-journal="${s.id}" placeholder="Notes, souvenirs, avis…">${esc((t.journal.find(j=>j.stepId===s.id)||{}).text||'')}</textarea></div>`).join('')||'<div class="empty-state">Ajoute des étapes pour créer le carnet.</div>';}
function renderSettings(){const f=$('#settingsForm'); ['autosaveMinutes','carSpeed','trainSpeed','walkSpeed'].forEach(k=>{if(f.elements[k])f.elements[k].value=state.settings[k]??''})}
function saveSettings(e){e.preventDefault(); const f=e.target; ['autosaveMinutes','carSpeed','trainSpeed','walkSpeed'].forEach(k=>state.settings[k]=U.num(f.elements[k].value)); persist('Paramètres enregistrés.')}
function renderAccount(){const box=$('#accountPanel'), user=Cloud.getUser(); box.innerHTML=user?`<div class="step-row"><div class="row-head"><div><strong>${esc(user.displayName||'Compte Google')}</strong><p class="muted">${esc(user.email||'')}</p></div>${user.photoURL?`<img src="${esc(user.photoURL)}" style="width:54px;height:54px;border-radius:50%">`:''}</div><div class="button-row"><button class="button" data-action="signout">Déconnexion</button><button class="button button--danger" data-action="deleteCloud">Réinitialiser le compte</button></div></div>`:loginGate();}
async function loadCommunity(){try{community=await Cloud.listCommunityTrips(); renderCommunity();}catch(e){show('Communauté indisponible : '+(e.message||e),'error')}}
function renderCommunity(){const grid=$('#communityGrid'); if(!grid)return; const user=Cloud.getUser(); $('#communityAdminPanel').hidden=!(user?.email==='lucas.scribe01@gmail.com'); if(user?.email==='lucas.scribe01@gmail.com') $('#communityAdminPanel').innerHTML='<strong>Mode admin actif</strong><p class="muted">Tu peux retirer une publication problématique.</p>'; const countries=[...new Set(community.map(c=>c.country).filter(Boolean))].sort(); const countrySel=$('#communityCountryFilter'); const current=countrySel.value; countrySel.innerHTML='<option value="">Tous les pays</option>'+countries.map(c=>`<option>${esc(c)}</option>`).join(''); countrySel.value=current; let list=[...community]; const q=$('#communitySearchInput').value.toLowerCase(), cat=$('#communityCategoryFilter').value, country=countrySel.value, sort=$('#communitySortFilter').value; if(q)list=list.filter(c=>JSON.stringify(c).toLowerCase().includes(q)); if(cat)list=list.filter(c=>c.category===cat); if(country)list=list.filter(c=>c.country===country); list.sort((a,b)=>sort==='recent'?(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0):(b.score||0)-(a.score||0)); grid.innerHTML=list.map(c=>`<article class="community-card"><div class="community-card__cover" ${c.coverImage?`style="background-image:url('${esc(c.coverImage)}')"`:''}></div><h3>${esc(c.title)}</h3><p class="muted">${esc(c.country||'Monde')} · ${esc(c.category||'voyage')} · tendance ${c.score||0}</p><p>${esc(c.description||'Itinéraire partagé par la communauté.')}</p><div class="button-row"><button class="button" data-vote="${c.id}:1">+ Tendance</button><button class="button" data-vote="${c.id}:-1">−</button>${c.allowCopy?`<button class="button button--primary" data-copy-community="${c.id}">Copier</button>`:''}${(user?.uid===c.ownerUid||user?.email==='lucas.scribe01@gmail.com')?`<button class="button button--danger" data-remove-community="${c.id}">Retirer</button>`:''}</div></article>`).join('')||'<div class="empty-state">Aucun voyage communautaire pour le moment.</div>';}
function openPublish(){const t=activeTrip(); if(!t)return show('Sélectionne un voyage à partager.','error'); const f=$('#publishForm'); f.reset(); f.elements.title.value=t.name; f.elements.country.value=t.area; f.elements.coverImage.value=t.coverImage; f.elements.description.value=t.description; $('#publishDialog').showModal();}
async function publishCommunity(e){e.preventDefault(); const t=activeTrip(); if(!t)return; const f=e.target; try{await Cloud.publishCommunityTrip(t,{title:f.title.value,country:f.country.value,category:f.category.value,coverImage:f.coverImage.value,description:f.description.value,hideBudget:f.hideBudget.checked,allowCopy:f.allowCopy.checked}); $('#publishDialog').close(); show('Voyage publié dans la communauté.'); await loadCommunity();}catch(err){show('Publication impossible : '+(err.message||err),'error')}}
function renderSearch(){const q=$('#globalSearchInput').value.trim().toLowerCase(), out=$('#globalSearchResults'); if(!q){out.hidden=true;out.innerHTML='';return;} const results=[]; state.trips.forEach(t=>{if(t.name.toLowerCase().includes(q)||t.area.toLowerCase().includes(q))results.push({label:`Voyage · ${t.name}`,go:'trip',trip:t.id}); t.steps.forEach(s=>{if((s.name+s.address+s.notes).toLowerCase().includes(q))results.push({label:`Étape · ${s.name}`,go:'itinerary',trip:t.id})}); t.expenses.forEach(e=>{if((e.label+e.category+e.note).toLowerCase().includes(q))results.push({label:`Dépense · ${e.label}`,go:'budget',trip:t.id})});}); out.innerHTML=results.slice(0,8).map(r=>`<button data-search-go="${r.go}" data-search-trip="${r.trip}">${esc(r.label)}</button>`).join('')||'<button>Aucun résultat</button>'; out.hidden=false;}
function delegated(e){
 const el=e.target.closest('button,input,textarea'); if(!el)return; const ds=el.dataset;
 if(ds.action==='signin')Cloud.signIn().catch(x=>show(x.message,'error')); if(ds.action==='signout')Cloud.signOut(); if(ds.action==='newTrip')newTrip(); if(ds.action==='step')openStep(); if(ds.action==='expense')openExpense(); if(ds.action==='deleteCloud'){if(confirm('Supprimer les données Firebase de ce compte ?'))Cloud.deleteState().then(()=>{state=Store.defaults();saveLocal();renderAll()})}
 if(ds.go)switchView(ds.go); if(ds.template){const tpl=templates.find(t=>t.name===ds.template); const trip=Store.createTrip({name:tpl.name+' '+new Date().getFullYear(),style:tpl.style}); state.trips.push(trip); state.activeTripId=trip.id; persist('Modèle créé.'); switchView('trip')}
 if(ds.openTrip){state.activeTripId=ds.openTrip;persist();switchView('trip')} if(ds.dupTrip){const t=state.trips.find(x=>x.id===ds.dupTrip); if(t){const c=Store.normalizeTrip({...JSON.parse(JSON.stringify(t)),id:U.uid(),name:t.name+' copie'}); state.trips.push(c);state.activeTripId=c.id;persist('Voyage dupliqué.')}} if(ds.delTrip){if(confirm('Supprimer ce voyage ?')){state.trips=state.trips.filter(t=>t.id!==ds.delTrip);state.activeTripId=state.trips[0]?.id||null;persist('Voyage supprimé.')}}
 if(ds.editStep)openStep(ds.editStep); if(ds.delStep){const t=activeTrip(); t.steps=t.steps.filter(s=>s.id!==ds.delStep);persist('Étape supprimée.')} if(ds.upStep||ds.downStep){const t=activeTrip(); const id=ds.upStep||ds.downStep; const i=t.steps.findIndex(s=>s.id===id); const j=ds.upStep?i-1:i+1; if(i>=0&&j>=0&&j<t.steps.length){[t.steps[i],t.steps[j]]=[t.steps[j],t.steps[i]];persist('Ordre modifié.')}} if(ds.addStepDate!==undefined){openStep(); $('#stepForm').elements.arrivalDate.value=ds.addStepDate; $('#stepForm').elements.departureDate.value=ds.addStepDate;}
 if(ds.editExpense)openExpense(ds.editExpense); if(ds.delExpense){const t=activeTrip(); t.expenses=t.expenses.filter(x=>x.id!==ds.delExpense);persist('Dépense supprimée.')}
 if(ds.vote){const [id,d]=ds.vote.split(':'); Cloud.voteCommunityTrip(id,Number(d)).then(loadCommunity).catch(x=>show(x.message,'error'))} if(ds.copyCommunity){const c=community.find(x=>x.id===ds.copyCommunity); if(c?.trip){const trip=Store.normalizeTrip({...c.trip,id:U.uid(),name:c.trip.name+' — copie'}); state.trips.push(trip);state.activeTripId=trip.id;persist('Voyage copié.')}} if(ds.removeCommunity){if(confirm('Retirer cette publication ?'))Cloud.removeCommunityTrip(ds.removeCommunity).then(loadCommunity).catch(x=>show(x.message,'error'))}
 if(ds.searchGo){state.activeTripId=ds.searchTrip; $('#globalSearchResults').hidden=true; $('#globalSearchInput').value=''; persist(); switchView(ds.searchGo)}
 if(ds.addCheckItem){const t=activeTrip(),b=t.checklists.find(x=>x.id===ds.addCheckItem); b.items.push({id:U.uid(),text:'Nouvelle tâche',done:false});persist('Tâche ajoutée.')} if(ds.delCheckBlock){const t=activeTrip();t.checklists=t.checklists.filter(b=>b.id!==ds.delCheckBlock);persist('Bloc supprimé.')} if(ds.delCheckItem){const [bid,iid]=ds.delCheckItem.split(':'); const b=activeTrip().checklists.find(x=>x.id===bid); b.items=b.items.filter(i=>i.id!==iid);persist('Tâche supprimée.')}
 if(ds.geo){const g=JSON.parse(ds.geo); const f=$('#stepForm'); f.elements.name.value=g.name; f.elements.address.value=g.address; f.elements.lat.value=g.lat; f.elements.lng.value=g.lng; $('#geocodeResults').innerHTML='';}
}
document.addEventListener('change',e=>{const ds=e.target.dataset,t=activeTrip(); if(!t)return; if(ds.checkItem){const[bid,iid]=ds.checkItem.split(':'); const it=t.checklists.find(b=>b.id===bid)?.items.find(i=>i.id===iid); if(it){it.done=e.target.checked;persist()}}});
document.addEventListener('input',e=>{const ds=e.target.dataset,t=activeTrip(); if(!t)return; if(ds.checkTitle){const b=t.checklists.find(x=>x.id===ds.checkTitle); if(b){b.title=e.target.value;scheduleSave()}} if(ds.checkText){const[bid,iid]=ds.checkText.split(':'); const it=t.checklists.find(b=>b.id===bid)?.items.find(i=>i.id===iid); if(it){it.text=e.target.value;scheduleSave()}} if(ds.journal){let j=t.journal.find(x=>x.stepId===ds.journal); if(!j){j={stepId:ds.journal,text:''};t.journal.push(j)} j.text=e.target.value; scheduleSave();}});
window.addEventListener('DOMContentLoaded',init);
})();
