(function(){
  const SDK='10.12.5', USER_COLL='travelPlannerUsers', COMMUNITY='communityTrips';
  let mods=null, app=null, auth=null, db=null, user=null, authReady=null; const listeners=new Set();
  const cfg=()=>window.TRAVEL_PLANNER_FIREBASE_CONFIG||{};
  const ok=()=>!!(cfg().apiKey&&cfg().authDomain&&cfg().projectId&&cfg().appId);
  async function loadMods(){ if(mods) return mods; const [a,au,fs]=await Promise.all([import(`https://www.gstatic.com/firebasejs/${SDK}/firebase-app.js`),import(`https://www.gstatic.com/firebasejs/${SDK}/firebase-auth.js`),import(`https://www.gstatic.com/firebasejs/${SDK}/firebase-firestore.js`)]); mods={a,au,fs}; return mods; }
  function emit(){listeners.forEach(fn=>fn({user,configured:ok()}));}
  async function init(){ if(auth&&db) return {auth,db,user}; if(!ok()) throw new Error('Configuration Firebase absente.'); const {a,au,fs}=await loadMods(); app=a.getApps().length?a.getApp():a.initializeApp(cfg()); auth=au.getAuth(app); db=fs.getFirestore(app); try{await au.setPersistence(auth,au.browserLocalPersistence)}catch(e){} if(!authReady){ authReady=new Promise(resolve=>{au.onAuthStateChanged(auth,u=>{user=u;emit();resolve(u);});}); } await authReady; return {auth,db,user}; }
  async function waitForAuthState(){await init(); return user;}
  async function signIn(){await init(); const {au}=await loadMods(); const p=new au.GoogleAuthProvider(); p.setCustomParameters({prompt:'select_account'}); try{const r=await au.signInWithPopup(auth,p); user=r.user; emit(); return user;}catch(e){ if(['auth/popup-blocked','auth/cancelled-popup-request','auth/operation-not-supported-in-this-environment'].includes(e.code)){await au.signInWithRedirect(auth,p);return null;} throw e; }}
  async function signOut(){await init(); const {au}=await loadMods(); await au.signOut(auth); user=null; emit();}
  function requireUser(){if(!user) throw new Error('Connexion Google requise.');}
  async function saveState(state){await init(); requireUser(); const {fs}=await loadMods(); const ref=fs.doc(db,USER_COLL,user.uid); const payload={ownerUid:user.uid,ownerEmail:user.email||'',schema:'travelPlannerState',schemaVersion:1,clientUpdatedAt:new Date().toISOString(),updatedAt:fs.serverTimestamp(),state:JSON.parse(JSON.stringify(state))}; await fs.setDoc(ref,payload,{merge:true}); return payload;}
  async function loadState(){await init(); requireUser(); const {fs}=await loadMods(); const snap=await fs.getDoc(fs.doc(db,USER_COLL,user.uid)); return snap.exists()?{state:snap.data().state,clientUpdatedAt:snap.data().clientUpdatedAt}:null;}
  async function deleteState(){await init(); requireUser(); const {fs}=await loadMods(); await fs.deleteDoc(fs.doc(db,USER_COLL,user.uid));}
  function publicTripPayload(trip,options={}){const copy=JSON.parse(JSON.stringify(trip)); if(options.hideBudget){copy.maxBudget=0;copy.expenses=[];} copy.checklists=[]; copy.journal=[]; if(options.hideNotes) copy.steps=(copy.steps||[]).map(s=>({...s,notes:''})); return copy;}
  async function publishCommunityTrip(trip,meta){await init(); requireUser(); const {fs}=await loadMods(); const ref=fs.doc(fs.collection(db,COMMUNITY)); const data={id:ref.id,ownerUid:user.uid,ownerEmail:user.email||'',ownerName:user.displayName||user.email||'Utilisateur',title:meta.title||trip.name,country:meta.country||trip.area||'',category:meta.category||'roadtrip',coverImage:meta.coverImage||trip.coverImage||'',description:meta.description||trip.description||'',allowCopy:meta.allowCopy!==false,hideBudget:!!meta.hideBudget,votes:{},score:0,createdAt:fs.serverTimestamp(),updatedAt:fs.serverTimestamp(),trip:publicTripPayload(trip,meta)}; await fs.setDoc(ref,data); return data;}
  async function listCommunityTrips(){await init(); const {fs}=await loadMods(); const snap=await fs.getDocs(fs.query(fs.collection(db,COMMUNITY),fs.limit(100))); return snap.docs.map(d=>({id:d.id,...d.data()}));}
  async function voteCommunityTrip(id,delta){await init(); requireUser(); const {fs}=await loadMods(); const ref=fs.doc(db,COMMUNITY,id); const snap=await fs.getDoc(ref); if(!snap.exists()) throw new Error('Publication introuvable.'); const data=snap.data(); const votes=data.votes||{}; votes[user.uid]=Math.max(-1,Math.min(1,Number(delta)||0)); const score=Object.values(votes).reduce((a,b)=>a+Number(b||0),0); await fs.updateDoc(ref,{votes,score,updatedAt:fs.serverTimestamp()});}
  async function removeCommunityTrip(id){await init(); requireUser(); const {fs}=await loadMods(); await fs.deleteDoc(fs.doc(db,COMMUNITY,id));}
  function onAuthChange(fn){listeners.add(fn); fn({user,configured:ok()}); return ()=>listeners.delete(fn);}
  function getUser(){return user;}
  window.TravelCloudSync={init,waitForAuthState,signIn,signOut,saveState,loadState,deleteState,getUser,onAuthChange,publishCommunityTrip,listCommunityTrips,voteCommunityTrip,removeCommunityTrip,isConfigured:ok};
})();
