(function(){
  const U=window.TravelUtils;
  const defaults=()=>({version:413,activeTripId:null,settings:{theme:'light',autosaveMinutes:3,carSpeed:80,trainSpeed:110,walkSpeed:5},trips:[]});
  function normalizeStep(s={}){return {id:s.id||U.uid(),name:s.name||'Nouvelle étape',type:s.type||'ville',address:s.address||'',lat:s.lat??'',lng:s.lng??'',arrivalDate:s.arrivalDate||s.date||'',arrivalTime:s.arrivalTime||'',departureDate:s.departureDate||s.arrivalDate||s.date||'',departureTime:s.departureTime||'',cost:U.num(s.cost),priority:s.priority||'indispensable',notes:s.notes||'',color:s.color||'#0ea5a7'};}
  function normalizeExpense(e={}){return {id:e.id||U.uid(),label:e.label||'Dépense',category:e.category||'autres',planned:U.num(e.planned??e.amount),actual:U.num(e.actual),status:e.status||'prévue',paidBy:e.paidBy||'',sharedWith:Array.isArray(e.sharedWith)?e.sharedWith:U.parsePeople(e.sharedWith),date:e.date||'',note:e.note||''};}
  function defaultChecklists(){return [{id:U.uid(),title:'Documents',items:[{id:U.uid(),text:'Passeport / carte d’identité',done:false},{id:U.uid(),text:'Billets et réservations',done:false}]},{id:U.uid(),title:'Avant départ',items:[{id:U.uid(),text:'Vérifier météo',done:false},{id:U.uid(),text:'Préparer chargeurs',done:false}]}];}
  function normalizeTrip(t={}){const id=t.id||U.uid(); const travellersNames=Array.isArray(t.travellersNames)?t.travellersNames:U.parsePeople(t.travellersNames); return {id,name:t.name||'Nouveau voyage',area:t.area||'',coverImage:t.coverImage||'',startDate:t.startDate||'',endDate:t.endDate||'',travellers:Math.max(1,U.num(t.travellers)||travellersNames.length||1),travellersNames, maxBudget:U.num(t.maxBudget),currency:t.currency||'€',status:t.status||'brouillon',style:t.style||'équilibré',pace:t.pace||'normal',interests:t.interests||'',description:t.description||'',steps:Array.isArray(t.steps)?t.steps.map(normalizeStep):[],expenses:Array.isArray(t.expenses)?t.expenses.map(normalizeExpense):[],checklists:Array.isArray(t.checklists)?t.checklists.map(b=>({id:b.id||U.uid(),title:b.title||'Liste',items:Array.isArray(b.items)?b.items.map(i=>({id:i.id||U.uid(),text:i.text||'Tâche',done:!!i.done})):[]})):defaultChecklists(),journal:Array.isArray(t.journal)?t.journal:[]};}
  function normalize(state){const s=Object.assign(defaults(),state||{}); s.settings=Object.assign(defaults().settings,s.settings||{}); s.trips=Array.isArray(s.trips)?s.trips.map(normalizeTrip):[]; if(!s.activeTripId||!s.trips.some(t=>t.id===s.activeTripId)) s.activeTripId=s.trips[0]?.id||null; return s;}
  const load=()=>normalize(JSON.parse(localStorage.getItem('travelPlanner:lastCache')||'null'));
  const save=s=>{const n=normalize(s); localStorage.setItem('travelPlanner:lastCache',JSON.stringify(n)); return n;};
  const getTrip=s=>normalize(s).trips.find(t=>t.id===s.activeTripId)||null;
  function createTrip(template={}){return normalizeTrip({name:template.name||'Nouveau voyage',area:template.area||'',status:'brouillon',style:template.style||'équilibré',currency:'€',travellers:1,steps:template.steps||[]});}
  window.TravelStorage={defaults,normalize,load,save,getTrip,createTrip,normalizeTrip,normalizeStep,normalizeExpense,defaultChecklists};
})();
